2022/03/23 12:59:03 [error] 33#33: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:9000", host: "backend.tmp.loc"
2022/03/23 12:59:18 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:9000", host: "backend.tmp.loc"
2022/03/23 12:59:20 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:9000", host: "backend.tmp.loc"
2022/03/23 12:59:20 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:9000", host: "backend.tmp.loc"
2022/03/23 12:59:20 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:9000", host: "backend.tmp.loc"
2022/03/23 12:59:21 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:9000", host: "backend.tmp.loc"
2022/03/23 12:59:21 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:9000", host: "backend.tmp.loc"
2022/03/23 12:59:21 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:9000", host: "backend.tmp.loc"
2022/03/23 12:59:21 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:9000", host: "backend.tmp.loc"
2022/03/23 12:59:21 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:9000", host: "backend.tmp.loc"
2022/03/23 12:59:22 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:9000", host: "backend.tmp.loc"
2022/03/23 12:59:22 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:9000", host: "backend.tmp.loc"
2022/03/23 12:59:22 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:9000", host: "backend.tmp.loc"
2022/03/23 12:59:22 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:9000", host: "backend.tmp.loc"
2022/03/23 12:59:23 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:9000", host: "backend.tmp.loc"
2022/03/23 12:59:23 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:9000", host: "backend.tmp.loc"
2022/03/23 12:59:24 [error] 35#35: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:9000", host: "backend.tmp.loc"
2022/03/23 12:59:39 [error] 32#32: *24 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:9000", host: "backend.tmp.loc"
2022/03/23 12:59:40 [error] 32#32: *24 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:9000", host: "backend.tmp.loc"
2022/03/23 12:59:40 [error] 32#32: *24 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:9000", host: "backend.tmp.loc"
2022/03/23 12:59:40 [error] 32#32: *24 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:9000", host: "backend.tmp.loc"
2022/03/23 12:59:40 [error] 32#32: *24 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:9000", host: "backend.tmp.loc"
2022/03/23 13:00:18 [error] 34#34: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:9000", host: "backend.tmp.loc"
2022/03/23 13:00:19 [error] 34#34: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:9000", host: "backend.tmp.loc"
2022/03/23 13:00:19 [error] 34#34: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:9000", host: "backend.tmp.loc"
2022/03/23 13:00:19 [error] 34#34: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:9000", host: "backend.tmp.loc"
2022/03/23 13:00:19 [error] 34#34: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:9000", host: "backend.tmp.loc"
2022/03/23 13:00:20 [error] 34#34: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.96.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.96.3:9000", host: "backend.tmp.loc"
2022/03/24 06:53:07 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:11 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:12 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:16 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:16 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:17 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:17 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:17 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:17 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:17 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:18 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:18 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:18 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:18 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:19 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:19 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:19 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:19 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:20 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:20 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:20 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:20 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:21 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:21 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:21 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:21 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:22 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:22 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:23 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:23 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:23 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:24 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:24 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:24 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:24 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:25 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:25 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:25 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:25 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:26 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:26 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:26 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:26 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:26 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:27 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:27 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:27 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:27 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:28 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:28 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:28 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:28 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:28 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:29 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:29 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:29 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:29 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:30 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:30 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:30 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:30 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:31 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:31 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:31 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:31 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:31 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:32 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:32 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:32 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:33 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:33 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:33 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:33 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:33 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:34 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:34 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:34 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:34 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:35 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:35 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:35 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:36 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:36 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:36 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:36 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:37 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:37 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:37 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:37 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:38 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:38 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:38 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:38 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:39 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:39 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:39 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:41 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:41 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:41 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:42 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:42 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:42 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:42 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:43 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:43 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:43 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:43 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:44 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:44 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:44 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:44 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:45 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:45 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:45 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:45 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:46 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:46 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:46 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:46 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:47 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:47 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:47 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:47 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:48 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:48 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:48 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:48 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:49 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:49 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:49 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:49 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:50 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:50 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:50 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:50 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:51 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:51 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:51 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:51 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:52 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:52 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:52 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:53 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:53 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:53 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:54 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:54 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:54 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:54 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:55 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:55 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:55 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:55 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:56 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:56 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:56 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:56 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:57 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:57 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:57 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:57 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:58 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:58 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:58 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:58 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:59 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:59 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:59 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:53:59 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:00 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:00 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:00 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:00 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:01 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:01 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:01 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:01 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:02 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:02 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:02 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:02 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:03 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:03 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:03 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:03 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:04 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:04 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:04 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:04 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:05 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:05 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:05 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:05 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:06 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:06 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:06 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:06 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:07 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:07 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:07 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:07 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:08 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:08 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:08 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:08 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:09 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:09 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:09 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:09 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:10 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:10 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:10 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:10 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:10 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:11 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:11 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:11 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:12 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:12 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:12 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:12 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:12 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:13 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:13 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:13 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:13 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:14 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:14 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:14 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:14 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:15 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:15 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:15 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:15 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:16 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:16 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:16 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:16 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:17 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:17 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:17 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:17 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:18 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:18 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:18 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:18 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:19 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:19 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:19 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:19 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:20 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:20 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:20 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:20 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:21 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:21 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:21 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:21 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:22 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:22 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:22 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:22 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:23 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/03/24 06:54:23 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.128.1, server: backend.tmp.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "backend.tmp.loc"
2022/07/13 21:29:45 [error] 33#33: *3 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.240.1, server: dd.local, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.240.3:9000", host: "dd.local"
